### ISSUE TITLE
rchitect 0.3.40 has just released, it contains wheels for python 3.11.

### ISSUE THREAD

**Issue by rrodrigueznt** [randy3k/rapi#24]
rchitect 0.3.40 has just released, it contains wheels for python 3.11.

_Originally posted by @randy3k in https://github.com/randy3k/rchitect/issues/22#issuecomment-1371767973_

Ubuntu 22.04 running on Termux on Samsung A52s with Android 13, aarch64, I'm getting:

```
pip 23.1.2 from /root/VirtualEnviron/lib/python3.11/site-packages/pip (python 3.11)
(VirtualEnviron) [root@localhost](mailto:root@localhost):~# python3 -m pip install -U rchitect --only-binary :all:
ERROR: Could not find a version that satisfies the requirement rchitect (from versions: none)
ERROR: No matching distribution found for architect
````

Should it be able to find the wheel?

**Comment by rrodrigueznt** [comment]
I think the answer to my question is NO. There is no `wheel` for my environment. I edited the original post to describe it better. Please, could anybody confirm? Thanks!

https://pypi.org/project/rchitect/#files

**Comment by rrodrigueznt** [comment]
As stated in Python Packaging User Guide » Tutorials » Installing Packages Source » [Distributions vs Wheels section](https://packaging.python.org/en/latest/tutorials/installing-packages/#source-distributions-vs-wheels):

"If pip does not find a wheel to install, it will locally build a wheel and cache it for future installs, instead of rebuilding the source distribution in the future."

Thus, I conclude that what I'm seeing [here](https://github.com/randy3k/radian/issues/428) is an issue when locally building a ```rchitect``` wheel.

I don't know if building a wheel is more demanding than any other possible alternative to install ```rchitect``` in my system. Any insight will be very welcome! Thanks in advance!

**Comment by randy3k** [comment]
why do you need to build the wheel? it should be easy to install it from source.

**Comment by rrodrigueznt** [comment]
I'm just trying to avoid screwing up things by following installation advice on the documentation. To the best of my current understanding, building a wheel implies a compilation. I guess what I'm getting is the same error. See below.

```
(VirtualEnviron) [root@localhost](mailto:root@localhost):~/git/rchitect# python3 setup.py install --user
/root/VirtualEnviron/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
Traceback (most recent call last):
  File "/root/git/rchitect/setup.py", line 32, in <module>
    setup(
  File "/root/VirtualEnviron/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/VirtualEnviron/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/root/VirtualEnviron/lib/python3.11/site-packages/setuptools/dist.py", line 486, in __init__
    _Distribution.__init__(
  File "/root/VirtualEnviron/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/root/VirtualEnviron/lib/python3.11/site-packages/setuptools/dist.py", line 925, in finalize_options
    ep(self)
  File "/root/VirtualEnviron/lib/python3.11/site-packages/setuptools/dist.py", line 945, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/root/VirtualEnviron/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/root/VirtualEnviron/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/root/VirtualEnviron/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "build.py", line 5, in <module>
    ffibuilder = FFI()
                 ^^^^^
  File "/root/VirtualEnviron/lib/python3.11/site-packages/cffi/api.py", line 48, in __init__
    import _cffi_backend as backend
ImportError: dlopen failed: library "/root/VirtualEnviron/lib/python3.11/site-packages/_cffi_backend.cpython-311.so" needed or dlopened by "/data/data/com.termux/files/usr/lib/libpython3.11.so.1.0" is not accessible for the namespace "(default)"
(VirtualEnviron) [root@localhost](mailto:root@localhost):~/git/rchitect#
```

I also guess the key part of the error message is "is not accessible for the namespace "(default)", but I'm not able to understand that message and act accordingly. I can locate ```_cffi_backend.cpython-311.so``` and ```libpython3.11.so.1.0```, but not able to understand the error message and correct the situation.

Any help is very welcome! Thanks!

**Comment by rrodrigueznt** [comment]
I think that I'm failing to build from source or build the wheel for the same reason: my Python installation is in Termux's files structure, while Python packages required by the compilation sit on Ubuntu 22.04 LTS running on Termux:
 
```
(VirtualEnviron) root@localhost:~# file /data/data/com.termux/files/usr/lib/libpython3.11.so.1.0
/data/data/com.termux/files/usr/lib/libpython3.11.so.1.0:
ELF shared object, 64-bit LSB arm64, for Android 24, built by NDK r25c (9519653), stripped
(VirtualEnviron) root@localhost:~# file /root/VirtualEnviron/lib/python3.11/site-packages/_cffi_backend.cpython-311.so
/root/VirtualEnviron/lib/python3.11/site-packages/_cffi_backend.cpython-311.so:
ELF shared object, 64-bit LSB arm64, for Android 24, built by NDK r25c (9519653), not stripped
(VirtualEnviron) root@localhost:~#
```
I can build from source in mac OS X, and on a standalone Ubuntu 22.04 LTS installation. Thus, there is no issue affecting ```rchitect```, but how I'm trying to use/build it. I will look for help at the concerned development site and insert references to this issue. Any insight and/or confirmation of my understanding of the issue is welcome! Thanks!
